name: Build Notchify App

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build App
        run: |
          set -euo pipefail
          xcodebuild -scheme Nook -configuration Release \
            -derivedDataPath build \
            build

      - name: Compress App
        run: |
          cd build/Build/Products/Release
          cp -R Nook.app Notchify.app
          ditto -c -k --sequesterRsrc --keepParent Notchify.app Notchify.zip
          ditto -c -k --sequesterRsrc --keepParent Nook.app Nook.zip

      - name: Upload Notchify.zip
        uses: actions/upload-artifact@v4
        with:
          name: Notchify-App
          path: build/Build/Products/Release/Notchify.zip
